CREATE TABLE IF not EXISTS users (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Nickname char(20) UNIQUE NOT NULL,
    FirstName char(20) NOT NULL,
    LastName char(20)  NOT NULL,
    Email char(50) UNIQUE NOT NULL,
    Password char(100),
    Age INTEGER,
    Gender TEXT CHECK(Gender IN ('male','female'))
);

CREATE TABLE IF NOT EXISTS Session(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    token TEXT,
    Expired_At DATE,
    ID_User INTEGER UNIQUE,
    FOREIGN KEY (ID_User) REFERENCES users(ID) ON DELETE CASCADE ON UPDATE CASCADE 
);

CREATE TABLE IF NOT EXISTS Posts (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Title char(50),
    Content TEXT, 
    Create_at INTEGER  ,
    User_id INTEGER,
    FOREIGN KEY (User_id) REFERENCES users(ID) ON DELETE CASCADE ON UPDATE CASCADE 
);

CREATE TABLE IF NOT EXISTS Category(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name_Category varchar(20) UNIQUE
);

CREATE TABLE IF NOT EXISTS PostCategory(
    ID_Post INTEGER,
    ID_Category INTEGER,
    PRIMARY KEY (ID_Post, ID_Category),
    FOREIGN KEY (ID_Post) REFERENCES Posts(ID) ON DELETE CASCADE ON UPDATE CASCADE, 
    FOREIGN KEY (ID_Category) REFERENCES Category(ID) ON DELETE CASCADE ON UPDATE CASCADE 
);

CREATE TABLE IF NOT EXISTS Comment(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Content TEXT,
    DateCreation INTEGER,
    ID_User INTEGER,    
    ID_Post INTEGER,
    FOREIGN KEY (ID_User) REFERENCES users(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ID_Post) REFERENCES Posts(ID) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE IF NOT EXISTS Chat (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    User1_ID INTEGER NOT NULL,
    User2_ID INTEGER NOT NULL,
    Created_At INTEGER,
    UNIQUE(User1_ID, User2_ID),
    FOREIGN KEY (User1_ID) REFERENCES users(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (User2_ID) REFERENCES users(ID) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE IF NOT EXISTS Messages (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Chat_ID INTEGER NOT NULL,
    Sender_ID INTEGER NOT NULL,
    Content TEXT NOT NULL,
    Sent_At INTEGER NOT NULL,
    FOREIGN KEY (Chat_ID) REFERENCES Chat(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (Sender_ID) REFERENCES users(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT OR IGNORE INTO Category (Name_Category) VALUES ('Coding');
INSERT OR IGNORE INTO Category (Name_Category) VALUES ('Innovation');
INSERT OR IGNORE INTO Category (Name_Category) VALUES ('Betcoin');
INSERT OR IGNORE INTO Category (Name_Category) VALUES ('kids');
INSERT OR IGNORE INTO Category (Name_Category) VALUES ('movie');
INSERT OR IGNORE INTO Category (Name_Category) VALUES ('sport');
INSERT OR IGNORE INTO Category (Name_Category) VALUES ('food');